group=de.cadentem

minecraft_version=1.20.1
neo_version=47.1.65

# Mappings
mapping_channel=parchment
mapping_version=2023.09.03-1.20.1

# Mod
mod_name=Additional Attributes
mod_author=Cadentem
mod_id=additional_attributes
mod_description=Adds additional attriutes to the game
mod_license=MIT License

mod_version=1.3.4+if.1

# Dependencies
parchment_version=2022.11.27

mixin_squared_version=0.1.1
mixin_extras_version=0.4.1

# Optional Dependencies
curios_version=5.4.7

# Jar
file_name=additional_attributes

# Gradle
org.gradle.daemon=false
org.gradle.jvmargs=-Xmx3G